[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
duct = "0.13.7"
chrono = "0.4.38"
bunt = "0.2.8"
color-eyre = "0.6.3"
